export const ShopActionTypes = {
  // CHANGE_PARAMS: "CHANGE_PARAMS",
  //USING REGULAR OBSERVABLE PATTERN
  // UPDATE_COLLECTIONS: "UPDATE_COLLECTIONS",

  //USING ASYNCHRONOUS REDUX HANDLE
  FETCH_COLLECTIONS_STARTS: "FETCH_COLLECTIONS_STARTS",
  FETCH_COLLECTIONS_SUCCESS: "FETCH_COLLECTIONS_SUCCESS",
  FETCH_COLLECTIONS_FAILURE: "FETCH_COLLECTIONS_FAILURE",
};

//EXPLAIN ASYNCHRONOUS REDUX HANDLE
//1. Make 3 actions with start, sucess, and failure
