export const CartActionTypes = {
  TOGGLE_CART_DROP_DOWN: "TOGGLE_CART_DROP_DOWN",
  ADD_ITEMS_TO_CART: "ADD_ITEMS_TO_CART:",
  CLEAR_ITEM_FROM_CART: "CLEAR_ITEM_FROM_CART",
  REMOVE_ITEM: "REMOVE_ITEM",
};
